package org.skylon07.familymapclient;

import models.Event;
import models.Person;

public class TestData {
    // a special thanks to python for making text to copy-paste here...
    // (ideally I'd use the server's "load" endpoint, but I didn't want to interfere
    // with other data I had loaded for debugging reasons... and I don't have time to
    // rewrite everything now that it's all working)
    public static Person[] persons = {
            new Person(
                    "root",
                    "usersName",
                    "Root",
                    "First",
                    "m",
                    "father-root",
                    "mother-root",
                    null
            ),
            new Person(
                    "father-root",
                    "usersName",
                    "FatherOfRoot",
                    "Second",
                    "m",
                    "father-father-root",
                    "mother-father-root",
                    "mother-root"
            ),
            new Person(
                    "father-father-root",
                    "usersName",
                    "FatherOfFatherOfRoot",
                    "Third",
                    "m",
                    "father-father-father-root",
                    "mother-father-father-root",
                    "mother-father-root"
            ),
            new Person(
                    "father-father-father-root",
                    "usersName",
                    "FatherOfFatherOfFatherOfRoot",
                    "Fourth",
                    "m",
                    "father-father-father-father-root",
                    "mother-father-father-father-root",
                    "mother-father-father-root"
            ),
            new Person(
                    "father-father-father-father-root",
                    "usersName",
                    "FatherOfFatherOfFatherOfFatherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-father-father-father-root"
            ),
            new Person(
                    "mother-father-father-father-root",
                    "usersName",
                    "MotherOfFatherOfFatherOfFatherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-father-father-father-root"
            ),
            new Person(
                    "mother-father-father-root",
                    "usersName",
                    "MotherOfFatherOfFatherOfRoot",
                    "Fourth",
                    "f",
                    "father-mother-father-father-root",
                    "mother-mother-father-father-root",
                    "father-father-father-root"
            ),
            new Person(
                    "father-mother-father-father-root",
                    "usersName",
                    "FatherOfMotherOfFatherOfFatherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-mother-father-father-root"
            ),
            new Person(
                    "mother-mother-father-father-root",
                    "usersName",
                    "MotherOfMotherOfFatherOfFatherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-mother-father-father-root"
            ),
            new Person(
                    "mother-father-root",
                    "usersName",
                    "MotherOfFatherOfRoot",
                    "Third",
                    "f",
                    "father-mother-father-root",
                    "mother-mother-father-root",
                    "father-father-root"
            ),
            new Person(
                    "father-mother-father-root",
                    "usersName",
                    "FatherOfMotherOfFatherOfRoot",
                    "Fourth",
                    "m",
                    "father-father-mother-father-root",
                    "mother-father-mother-father-root",
                    "mother-mother-father-root"
            ),
            new Person(
                    "father-father-mother-father-root",
                    "usersName",
                    "FatherOfFatherOfMotherOfFatherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-father-mother-father-root"
            ),
            new Person(
                    "mother-father-mother-father-root",
                    "usersName",
                    "MotherOfFatherOfMotherOfFatherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-father-mother-father-root"
            ),
            new Person(
                    "mother-mother-father-root",
                    "usersName",
                    "MotherOfMotherOfFatherOfRoot",
                    "Fourth",
                    "f",
                    "father-mother-mother-father-root",
                    "mother-mother-mother-father-root",
                    "father-mother-father-root"
            ),
            new Person(
                    "father-mother-mother-father-root",
                    "usersName",
                    "FatherOfMotherOfMotherOfFatherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-mother-mother-father-root"
            ),
            new Person(
                    "mother-mother-mother-father-root",
                    "usersName",
                    "MotherOfMotherOfMotherOfFatherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-mother-mother-father-root"
            ),
            new Person(
                    "mother-root",
                    "usersName",
                    "MotherOfRoot",
                    "Second",
                    "f",
                    "father-mother-root",
                    "mother-mother-root",
                    "father-root"
            ),
            new Person(
                    "father-mother-root",
                    "usersName",
                    "FatherOfMotherOfRoot",
                    "Third",
                    "m",
                    "father-father-mother-root",
                    "mother-father-mother-root",
                    "mother-mother-root"
            ),
            new Person(
                    "father-father-mother-root",
                    "usersName",
                    "FatherOfFatherOfMotherOfRoot",
                    "Fourth",
                    "m",
                    "father-father-father-mother-root",
                    "mother-father-father-mother-root",
                    "mother-father-mother-root"
            ),
            new Person(
                    "father-father-father-mother-root",
                    "usersName",
                    "FatherOfFatherOfFatherOfMotherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-father-father-mother-root"
            ),
            new Person(
                    "mother-father-father-mother-root",
                    "usersName",
                    "MotherOfFatherOfFatherOfMotherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-father-father-mother-root"
            ),
            new Person(
                    "mother-father-mother-root",
                    "usersName",
                    "MotherOfFatherOfMotherOfRoot",
                    "Fourth",
                    "f",
                    "father-mother-father-mother-root",
                    "mother-mother-father-mother-root",
                    "father-father-mother-root"
            ),
            new Person(
                    "father-mother-father-mother-root",
                    "usersName",
                    "FatherOfMotherOfFatherOfMotherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-mother-father-mother-root"
            ),
            new Person(
                    "mother-mother-father-mother-root",
                    "usersName",
                    "MotherOfMotherOfFatherOfMotherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-mother-father-mother-root"
            ),
            new Person(
                    "mother-mother-root",
                    "usersName",
                    "MotherOfMotherOfRoot",
                    "Third",
                    "f",
                    "father-mother-mother-root",
                    "mother-mother-mother-root",
                    "father-mother-root"
            ),
            new Person(
                    "father-mother-mother-root",
                    "usersName",
                    "FatherOfMotherOfMotherOfRoot",
                    "Fourth",
                    "m",
                    "father-father-mother-mother-root",
                    "mother-father-mother-mother-root",
                    "mother-mother-mother-root"
            ),
            new Person(
                    "father-father-mother-mother-root",
                    "usersName",
                    "FatherOfFatherOfMotherOfMotherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-father-mother-mother-root"
            ),
            new Person(
                    "mother-father-mother-mother-root",
                    "usersName",
                    "MotherOfFatherOfMotherOfMotherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-father-mother-mother-root"
            ),
            new Person(
                    "mother-mother-mother-root",
                    "usersName",
                    "MotherOfMotherOfMotherOfRoot",
                    "Fourth",
                    "f",
                    "father-mother-mother-mother-root",
                    "mother-mother-mother-mother-root",
                    "father-mother-mother-root"
            ),
            new Person(
                    "father-mother-mother-mother-root",
                    "usersName",
                    "FatherOfMotherOfMotherOfMotherOfRoot",
                    "Fifth",
                    "m",
                    null,
                    null,
                    "mother-mother-mother-mother-root"
            ),
            new Person(
                    "mother-mother-mother-mother-root",
                    "usersName",
                    "MotherOfMotherOfMotherOfMotherOfRoot",
                    "Fifth",
                    "f",
                    null,
                    null,
                    "father-mother-mother-mother-root"
            )
    };
    public static Event[] events = {
            new Event(
                    "birth-root",
                    "usersName",
                    "root",
                    -3,
                    15,
                    "USA",
                    "New York",
                    "Birth",
                    2000
            ),
            new Event(
                    "birth-father-root",
                    "usersName",
                    "father-root",
                    40,
                    -15,
                    "USA",
                    "New York",
                    "Birth",
                    1970
            ),
            new Event(
                    "marriage-father-root",
                    "usersName",
                    "father-root",
                    -49,
                    -38,
                    "USA",
                    "New York",
                    "Marriage",
                    1995
            ),
            new Event(
                    "death-father-root",
                    "usersName",
                    "father-root",
                    -5,
                    -36,
                    "USA",
                    "New York",
                    "Death",
                    2050
            ),
            new Event(
                    "birth-father-father-root",
                    "usersName",
                    "father-father-root",
                    35,
                    21,
                    "USA",
                    "New York",
                    "Birth",
                    1940
            ),
            new Event(
                    "marriage-father-father-root",
                    "usersName",
                    "father-father-root",
                    20,
                    -45,
                    "USA",
                    "New York",
                    "Marriage",
                    1965
            ),
            new Event(
                    "death-father-father-root",
                    "usersName",
                    "father-father-root",
                    -25,
                    -41,
                    "USA",
                    "New York",
                    "Death",
                    2020
            ),
            new Event(
                    "birth-father-father-father-root",
                    "usersName",
                    "father-father-father-root",
                    -20,
                    -39,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-father-father-father-root",
                    "usersName",
                    "father-father-father-root",
                    30,
                    -22,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-father-father-father-root",
                    "usersName",
                    "father-father-father-root",
                    -6,
                    47,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-father-father-father-root",
                    "usersName",
                    "father-father-father-father-root",
                    38,
                    -1,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-father-father-father-root",
                    "usersName",
                    "father-father-father-father-root",
                    -8,
                    41,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-father-father-father-root",
                    "usersName",
                    "father-father-father-father-root",
                    40,
                    -6,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-father-father-father-root",
                    "usersName",
                    "mother-father-father-father-root",
                    19,
                    9,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-father-father-father-root",
                    "usersName",
                    "mother-father-father-father-root",
                    -8,
                    41,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-father-father-father-root",
                    "usersName",
                    "mother-father-father-father-root",
                    -50,
                    -31,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-father-father-root",
                    "usersName",
                    "mother-father-father-root",
                    -2,
                    44,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-mother-father-father-root",
                    "usersName",
                    "mother-father-father-root",
                    30,
                    -22,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-mother-father-father-root",
                    "usersName",
                    "mother-father-father-root",
                    -41,
                    -7,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-mother-father-father-root",
                    "usersName",
                    "father-mother-father-father-root",
                    37,
                    -27,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-mother-father-father-root",
                    "usersName",
                    "father-mother-father-father-root",
                    -22,
                    -16,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-mother-father-father-root",
                    "usersName",
                    "father-mother-father-father-root",
                    24,
                    -36,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-mother-father-father-root",
                    "usersName",
                    "mother-mother-father-father-root",
                    -48,
                    -26,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-mother-father-father-root",
                    "usersName",
                    "mother-mother-father-father-root",
                    -22,
                    -16,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-mother-father-father-root",
                    "usersName",
                    "mother-mother-father-father-root",
                    -41,
                    -31,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-father-root",
                    "usersName",
                    "mother-father-root",
                    -2,
                    -15,
                    "USA",
                    "New York",
                    "Birth",
                    1940
            ),
            new Event(
                    "marriage-mother-father-root",
                    "usersName",
                    "mother-father-root",
                    20,
                    -45,
                    "USA",
                    "New York",
                    "Marriage",
                    1965
            ),
            new Event(
                    "death-mother-father-root",
                    "usersName",
                    "mother-father-root",
                    -2,
                    -6,
                    "USA",
                    "New York",
                    "Death",
                    2020
            ),
            new Event(
                    "birth-father-mother-father-root",
                    "usersName",
                    "father-mother-father-root",
                    -31,
                    -10,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-father-mother-father-root",
                    "usersName",
                    "father-mother-father-root",
                    -46,
                    27,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-father-mother-father-root",
                    "usersName",
                    "father-mother-father-root",
                    20,
                    45,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-father-mother-father-root",
                    "usersName",
                    "father-father-mother-father-root",
                    39,
                    -28,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-father-mother-father-root",
                    "usersName",
                    "father-father-mother-father-root",
                    40,
                    -41,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-father-mother-father-root",
                    "usersName",
                    "father-father-mother-father-root",
                    -47,
                    41,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-father-mother-father-root",
                    "usersName",
                    "mother-father-mother-father-root",
                    50,
                    -35,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-father-mother-father-root",
                    "usersName",
                    "mother-father-mother-father-root",
                    40,
                    -41,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-father-mother-father-root",
                    "usersName",
                    "mother-father-mother-father-root",
                    16,
                    -5,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-mother-father-root",
                    "usersName",
                    "mother-mother-father-root",
                    7,
                    30,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-mother-mother-father-root",
                    "usersName",
                    "mother-mother-father-root",
                    -46,
                    27,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-mother-mother-father-root",
                    "usersName",
                    "mother-mother-father-root",
                    -2,
                    -42,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-mother-mother-father-root",
                    "usersName",
                    "father-mother-mother-father-root",
                    10,
                    50,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-mother-mother-father-root",
                    "usersName",
                    "father-mother-mother-father-root",
                    -35,
                    20,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-mother-mother-father-root",
                    "usersName",
                    "father-mother-mother-father-root",
                    12,
                    22,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-mother-mother-father-root",
                    "usersName",
                    "mother-mother-mother-father-root",
                    -34,
                    28,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-mother-mother-father-root",
                    "usersName",
                    "mother-mother-mother-father-root",
                    -35,
                    20,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-mother-mother-father-root",
                    "usersName",
                    "mother-mother-mother-father-root",
                    -42,
                    37,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-root",
                    "usersName",
                    "mother-root",
                    -27,
                    -46,
                    "USA",
                    "New York",
                    "Birth",
                    1970
            ),
            new Event(
                    "marriage-mother-root",
                    "usersName",
                    "mother-root",
                    -49,
                    -38,
                    "USA",
                    "New York",
                    "Marriage",
                    1995
            ),
            new Event(
                    "death-mother-root",
                    "usersName",
                    "mother-root",
                    -40,
                    4,
                    "USA",
                    "New York",
                    "Death",
                    2050
            ),
            new Event(
                    "birth-father-mother-root",
                    "usersName",
                    "father-mother-root",
                    15,
                    -26,
                    "USA",
                    "New York",
                    "Birth",
                    1940
            ),
            new Event(
                    "marriage-father-mother-root",
                    "usersName",
                    "father-mother-root",
                    -33,
                    23,
                    "USA",
                    "New York",
                    "Marriage",
                    1965
            ),
            new Event(
                    "death-father-mother-root",
                    "usersName",
                    "father-mother-root",
                    49,
                    43,
                    "USA",
                    "New York",
                    "Death",
                    2020
            ),
            new Event(
                    "birth-father-father-mother-root",
                    "usersName",
                    "father-father-mother-root",
                    39,
                    -47,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-father-father-mother-root",
                    "usersName",
                    "father-father-mother-root",
                    11,
                    14,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-father-father-mother-root",
                    "usersName",
                    "father-father-mother-root",
                    2,
                    -1,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-father-father-mother-root",
                    "usersName",
                    "father-father-father-mother-root",
                    0,
                    38,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-father-father-mother-root",
                    "usersName",
                    "father-father-father-mother-root",
                    14,
                    -35,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-father-father-mother-root",
                    "usersName",
                    "father-father-father-mother-root",
                    1,
                    -26,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-father-father-mother-root",
                    "usersName",
                    "mother-father-father-mother-root",
                    39,
                    20,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-father-father-mother-root",
                    "usersName",
                    "mother-father-father-mother-root",
                    14,
                    -35,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-father-father-mother-root",
                    "usersName",
                    "mother-father-father-mother-root",
                    11,
                    -29,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-father-mother-root",
                    "usersName",
                    "mother-father-mother-root",
                    -50,
                    21,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-mother-father-mother-root",
                    "usersName",
                    "mother-father-mother-root",
                    11,
                    14,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-mother-father-mother-root",
                    "usersName",
                    "mother-father-mother-root",
                    -50,
                    29,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-mother-father-mother-root",
                    "usersName",
                    "father-mother-father-mother-root",
                    -35,
                    48,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-mother-father-mother-root",
                    "usersName",
                    "father-mother-father-mother-root",
                    23,
                    1,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-mother-father-mother-root",
                    "usersName",
                    "father-mother-father-mother-root",
                    -49,
                    35,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-mother-father-mother-root",
                    "usersName",
                    "mother-mother-father-mother-root",
                    -25,
                    38,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-mother-father-mother-root",
                    "usersName",
                    "mother-mother-father-mother-root",
                    23,
                    1,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-mother-father-mother-root",
                    "usersName",
                    "mother-mother-father-mother-root",
                    -17,
                    33,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-mother-root",
                    "usersName",
                    "mother-mother-root",
                    -15,
                    3,
                    "USA",
                    "New York",
                    "Birth",
                    1940
            ),
            new Event(
                    "marriage-mother-mother-root",
                    "usersName",
                    "mother-mother-root",
                    -33,
                    23,
                    "USA",
                    "New York",
                    "Marriage",
                    1965
            ),
            new Event(
                    "death-mother-mother-root",
                    "usersName",
                    "mother-mother-root",
                    29,
                    -23,
                    "USA",
                    "New York",
                    "Death",
                    2020
            ),
            new Event(
                    "birth-father-mother-mother-root",
                    "usersName",
                    "father-mother-mother-root",
                    -7,
                    -22,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-father-mother-mother-root",
                    "usersName",
                    "father-mother-mother-root",
                    45,
                    -44,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-father-mother-mother-root",
                    "usersName",
                    "father-mother-mother-root",
                    49,
                    41,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-father-mother-mother-root",
                    "usersName",
                    "father-father-mother-mother-root",
                    -45,
                    2,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-father-mother-mother-root",
                    "usersName",
                    "father-father-mother-mother-root",
                    4,
                    31,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-father-mother-mother-root",
                    "usersName",
                    "father-father-mother-mother-root",
                    5,
                    49,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-father-mother-mother-root",
                    "usersName",
                    "mother-father-mother-mother-root",
                    32,
                    41,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-father-mother-mother-root",
                    "usersName",
                    "mother-father-mother-mother-root",
                    4,
                    31,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-father-mother-mother-root",
                    "usersName",
                    "mother-father-mother-mother-root",
                    -31,
                    -41,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-mother-mother-root",
                    "usersName",
                    "mother-mother-mother-root",
                    -37,
                    14,
                    "USA",
                    "New York",
                    "Birth",
                    1910
            ),
            new Event(
                    "marriage-mother-mother-mother-root",
                    "usersName",
                    "mother-mother-mother-root",
                    45,
                    -44,
                    "USA",
                    "New York",
                    "Marriage",
                    1935
            ),
            new Event(
                    "death-mother-mother-mother-root",
                    "usersName",
                    "mother-mother-mother-root",
                    14,
                    1,
                    "USA",
                    "New York",
                    "Death",
                    1990
            ),
            new Event(
                    "birth-father-mother-mother-mother-root",
                    "usersName",
                    "father-mother-mother-mother-root",
                    -43,
                    -22,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-father-mother-mother-mother-root",
                    "usersName",
                    "father-mother-mother-mother-root",
                    14,
                    -24,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-father-mother-mother-mother-root",
                    "usersName",
                    "father-mother-mother-mother-root",
                    10,
                    15,
                    "USA",
                    "New York",
                    "Death",
                    1960
            ),
            new Event(
                    "birth-mother-mother-mother-mother-root",
                    "usersName",
                    "mother-mother-mother-mother-root",
                    -44,
                    28,
                    "USA",
                    "New York",
                    "Birth",
                    1880
            ),
            new Event(
                    "marriage-mother-mother-mother-mother-root",
                    "usersName",
                    "mother-mother-mother-mother-root",
                    14,
                    -24,
                    "USA",
                    "New York",
                    "Marriage",
                    1905
            ),
            new Event(
                    "death-mother-mother-mother-mother-root",
                    "usersName",
                    "mother-mother-mother-mother-root",
                    29,
                    24,
                    "USA",
                    "New York",
                    "Death",
                    1960
            )
    };
}
